#!/bin/python3 -W ignore

import PyPDF2
import sys

file = sys.argv[1]

PDF = PyPDF2.PdfFileReader( file, 'rb' )
PAGE_NUM = PDF.numPages

def checkSize():
    if (PAGE_NUM < 3):
        print('small')
    else:
        print('big')

checkSize()
