#!/bin/bash

folder="$HOME/Downloads/*.pdf" 

for file in $folder; do
  info=$(./pdfreader "$file")
  [ "$info" == "small" ] && mv "$file" $HOME/Documentos/PDF/small/
  [ "$info" == "big" ] && mv "$file" $HOME/Documentos/PDF/big/

done

