#!/bin/bash

folder="$HOME/Downloads/*.pdf" 

for file in $folder; do
  info=$(./pdfreader "$file")
  echo "$file - $info"
  # echo $(grep -o 'MEI' <<< "$info" ; grep -o -P '\d{2}\/\d{2}\/\d{4}' <<< "$info" ) | sed 's/[\/ ]/\-/g' 

done

